services:
  - type: web
    name: pong-backend
    runtime: node
    plan: free
    region: frankfurt
    rootDir: server
    buildCommand: npm install
    startCommand: npm run start
    autoDeployTrigger: commit
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 4000
      - key: CLIENT_URLS
        value: "*"

  - type: web
    name: pong-frontend
    runtime: node
    plan: free
    region: frankfurt
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeployTrigger: commit
    envVars:
      - key: NEXT_PUBLIC_SERVER_URL
        sync: false
